# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sarah Bardin
title: | Researcher, Human Services, Mathematica
         PhD Student, School of Geographical Sciences and Urban Planning, Arizona State University
email: sbardin@asu.edu
#website: www.github.com/SarahBardin

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SarahBardin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sarah-bardin
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Bardin_pic.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sarah and I'm a PhD Student in Geography at Arizona State University and Researcher at Mathematica. More to come... 

content:
  - title: Current Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Under development
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          XXXXX.
        description: | # this will include new lines to allow paragraphs
          Under development.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mathematica
        link: Mathematica.org
        sub_title: Researcher, Human Services
        caption: March 2021 - Present
        sub_title: Research Analyst, Human Services
        caption: January 2020 - March 2021
        sub_title: Data Analytics Developer/Senior Programmer, Human Services
        caption: March 2018 - December 2019
        sub_title: Research Associate/Programmer, Human Services
        caption: July 2015 - March 2018
        
        quote: >
          Improving **public well-being** by bringing the highest standards of **quality**, **objectivity**, and **excellence** to bear on the provision of information collection and analysis.
        description: | # this will include new lines to allow paragraphs
            Section under development.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Arizona State University, School of Geographical Sciences and Urban Planning
        caption: 2019 - Present
        sub_title: PhD Geography (expected Dec 2023)
        sub_title: MA Geography (2021)
        
        quote: >
          XXX
          description: | # this will include new lines to allow paragraphs
          XXX
          
      - layout: left
        sub_title: University of Chicago
        caption: 2011 - 2015
        sub_title: AB Public Policy, Departmental Honors
        sub_title: AB Political Science, General Honors
        
        quote: >
          XXX
          description: | # this will include new lines to allow paragraphs
          XXX
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Under development
      - Traveling
      - Baking
      - Hiking
   #  - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

   #   Look at this cool image  
   #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
