# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sarah Bardin
title:  Policy Researcher and PhD Student
email: sfbardin@asu.edu
#website: www.github.com/SarahBardin

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SarahBardin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sarah-bardin
orcid_username: 0000-0001-8657-1725

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Bardin_pic.png
about_content: | # this will include new lines to allow paragraphs
  As a spatial statistician and policy researcher by training, I bring deep analytic expertise in geographic data analysis, policy evaluation, and 
  measure development to my work. For the past 5 years, I've led the design and implementation of quantitative analyses to examine federal child 
  nutrition programs, child welfare service provision, and unintended and teen pregnancy prevention programs for federal and foundation clients.
  In addition to my professional research, I am currently pursuing my PhD in Geography at Arizona State University where I seek to advance
  the development of a Spatial Policy that brings an explicitly geographic approach to public policy research. My dissertation aims to
  offer a pathway to shift from simply identifying "what works" to knowing "what works where" to support improved evidence-based policy making.

content:
  - title: Current Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: Study of Nutrition and Activity in Childcare Settings in USDA’s Child and Adult Care Food Program (SNACS)-II
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Overall analytic lead for the second nationally representative, comprehensive assessment of the Child and Adult Care Food Program (CACFP).
      
         
         
        title: Child Welfare Study to Enhance Equity through Data (CW-SEED)
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Environmental scan task lead.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mathematica
        link: Mathematica.org
        sub_title: Researcher, Human Services
        caption: March 2021 - Present
        # sub_title: Research Analyst, Human Services
        # caption: January 2020 - March 2021
        # sub_title: Data Analytics Developer/Senior Programmer, Human Services
        # caption: March 2018 - December 2019
        # sub_title: Research Associate/Programmer, Human Services
        # caption: July 2015 - March 2018
        
        quote: >
          Improving <mark>public well-being</mark> by bringing the highest standards of <mark>quality, objectivity, and excellence</mark> to bear on the provision of information collection and analysis.
        description: | # this will include new lines to allow paragraphs
            Section under development.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2019 - Present
        sub_title: PhD Geography (expected Dec 2023)
                   MA Geography (2021)
        
        quote: >
          
          description: | # this will include new lines to allow paragraphs
          
          
      - layout: left
        title: University of Chicago
        caption: 2011 - 2015
        sub_title: AB Public Policy, Departmental Honors 
                   AB Political Science, General Honors
        
        quote: >
          
          description: | # this will include new lines to allow paragraphs
          
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Under development
      - Traveling
      - Baking
      - Hiking
   #  - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

   #   Look at this cool image  
   #   ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
